// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sshdzkuhxphbppcwnxnx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzaGR6a3VoeHBoYnBwY3dueG54Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MjYwMTgsImV4cCI6MjA2NDAwMjAxOH0.9p8eAnF1DgTPrbrn4f8iLzAlkIpgcl-nE5ek9tUpccY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);